import argparse
import pathlib

from client import Client

parser = argparse.ArgumentParser(
    description="This is the CLI-friendly client for testchat, a highly experimental and demonstrational chat program.",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument(
    "-i",
    "--ip",
    "--address",
    default="localhost",
    help="IP address of a testchat server.",
)
parser.add_argument(
    "-p",
    "--port",
    type=int,
    default=5500,
    help="Port that a testchat server is hosted through. Should be an integer.",
)
parser.add_argument(
    "-c",
    "--config",
    type=pathlib.Path,
    nargs="?",
    const="testchat-config.json",
    help="Optional path to a JSON configuation file generated by testchat. Config options will override arguments.",
)
args = parser.parse_args()


def main():
    config_path: pathlib.Path | None = args.config
    active_config = {
        "ip": args.ip,
        "port": args.port,
        "users": {},
    }


if __name__ == "__main__":
    main()
